### ISSUE TITLE
Documento ERS

### ISSUE THREAD

**Issue by AmeliReyesHernandez** [SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-v-a-k#1]
https://github.com/SistemasTecTlaxiaco/Loc-Serv/wiki

**Comment by edgarmauricio123** [comment]
Según la rubrica cuenta con 28 puntos de 30.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Falta solo acomodar la estructura de acuerdo a la plantilla proporcionada
